language:
  ruby

rvm:
  - '1.9'
  - '2.0'
  - '2.1'
  - ruby-head
  - rbx

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx

  fast_finish:
    true

script:
  rake test:all

install:
  gem install --prerelease --development lingo
